// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0w6JvtaS2R4DEX6kLqPus4DbhRIPXMt8',
    appId: '1:882923537217:android:5d402d2d74bfa57b6717c0',
    messagingSenderId: '882923537217',
    projectId: 'paper-ieee-vtc-2022',
    storageBucket: 'paper-ieee-vtc-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Nv1gBiKExHO3wNiKNGjkLyJqhts0v-w',
    appId: '1:882923537217:ios:fe41708447e7763a6717c0',
    messagingSenderId: '882923537217',
    projectId: 'paper-ieee-vtc-2022',
    storageBucket: 'paper-ieee-vtc-2022.appspot.com',
    iosClientId: '882923537217-hg8h2isn21tp021sphq1cpbe1u9q28d6.apps.googleusercontent.com',
    iosBundleId: 'app.begaz.obd.two.plugin.obd2PluginExample',
  );
}
